# Use new trusty images, should yield newer compilers and packages
sudo: required
dist: trusty
language: cpp

matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
      env: COMPILER=g++-4.9
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      env: COMPILER=g++-5

before_install:
  - sudo add-apt-repository ppa:george-edison55/cmake-3.x --yes
  - sudo apt-get update -qq
  - sudo apt-get install -y libsfml-dev cmake
  - wget https://github.com/google/protobuf/releases/download/v2.6.1/protobuf-2.6.1.tar.gz
  - tar -xvf protobuf-2.6.1.tar.gz
  - cd protobuf-2.6.1 && ./configure --prefix=/usr && make && sudo make install
  - cd ..
script:
  - mkdir install
  - mkdir build
  - cd build
  - cmake -DCMAKE_CXX_COMPILER=$COMPILER -DCMAKE_INSTALL_PREFIX=../install .. && make install